name: random_user_test_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-281.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^8.2.0
  dio: ^5.5.0
  get_it: ^7.6.7
  talker: ^4.3.2
  talker_dio_logger: ^4.3.2
  retrofit: ^4.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10
  hexcolor: ^3.0.1
  oktoast: ^3.4.0

  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.6
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  retrofit_generator: '^8.1.1'
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/

